services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  server:
    build: ./Portfolio.Server
    container_name: portfolio-server
    environment:
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
    depends_on:
      - db
  client:
    build: ./Portfolio.Client
    container_name: portfolio-client
    ports:
      - "127.0.0.1:2137:80"
    depends_on:
      - server