// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Server.Data;

#nullable disable

namespace Portfolio.Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260319195509_AddGithubAndLinkedinNames")]
    partial class AddGithubAndLinkedinNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Server.Models.ProfileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GithubUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkedinProfile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description",
                            GithubUsername = "",
                            LinkedinProfile = "",
                            Location = "City, Country",
                            Name = "Name",
                            Phone = "Phone number",
                            PhotoUrl = "",
                            Title = "Title"
                        });
                });

            modelBuilder.Entity("Portfolio.Server.Models.ProjectData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DemoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GithubUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Portfolio.Server.Models.TechCategoryData", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("TechCategories");

                    b.HasData(
                        new
                        {
                            Name = "language"
                        },
                        new
                        {
                            Name = "framework"
                        },
                        new
                        {
                            Name = "database"
                        },
                        new
                        {
                            Name = "devops"
                        },
                        new
                        {
                            Name = "ides & tools"
                        });
                });

            modelBuilder.Entity("Portfolio.Server.Models.TechData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DarkColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LightColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "language",
                            DarkColor = "#a179dc",
                            IconUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/csharp/csharp-original.svg",
                            LightColor = "#68217a",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Category = "framework",
                            DarkColor = "#a68aee",
                            IconUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/dot-net/dot-net-original.svg",
                            LightColor = "#512bd4",
                            Name = "ASP.NET"
                        },
                        new
                        {
                            Id = 3,
                            Category = "framework",
                            DarkColor = "#61dafb",
                            IconUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg",
                            LightColor = "#0b8da8",
                            Name = "React"
                        },
                        new
                        {
                            Id = 4,
                            Category = "language",
                            DarkColor = "#6ba5e7",
                            IconUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg",
                            LightColor = "#3178c6",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 5,
                            Category = "database",
                            DarkColor = "#CC2927",
                            IconUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/microsoftsqlserver/microsoftsqlserver-original.svg",
                            LightColor = "#b82422",
                            Name = "SQL Server"
                        },
                        new
                        {
                            Id = 6,
                            Category = "devops",
                            DarkColor = "#2496ed",
                            IconUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg",
                            LightColor = "#1a70b2",
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 7,
                            Category = "language",
                            DarkColor = "#FF7043",
                            IconUrl = "src/assets/rust.svg",
                            LightColor = "#d15b36",
                            Name = "Rust"
                        },
                        new
                        {
                            Id = 8,
                            Category = "framework",
                            DarkColor = "#ffffff",
                            IconUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/unity/unity-original.svg",
                            LightColor = "#000000",
                            Name = "Unity"
                        },
                        new
                        {
                            Id = 9,
                            Category = "framework",
                            DarkColor = "#a68aee",
                            IconUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/dotnetcore/dotnetcore-original.svg",
                            LightColor = "#512bd4",
                            Name = ".NET Core"
                        },
                        new
                        {
                            Id = 10,
                            Category = "ides & tools",
                            DarkColor = "#ba7df6",
                            IconUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/visualstudio/visualstudio-original.svg",
                            LightColor = "#5C2D91",
                            Name = "Visual Studio"
                        },
                        new
                        {
                            Id = 11,
                            Category = "ides & tools",
                            DarkColor = "#3da8ff",
                            IconUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vscode/vscode-original.svg",
                            LightColor = "#0078D7",
                            Name = "VS Code"
                        },
                        new
                        {
                            Id = 12,
                            Category = "ides & tools",
                            DarkColor = "#ff4d80",
                            IconUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/rider/rider-original.svg",
                            LightColor = "#E11350",
                            Name = "Rider"
                        },
                        new
                        {
                            Id = 13,
                            Category = "ides & tools",
                            DarkColor = "#4285F4",
                            IconUrl = "src/assets/antigravity.svg",
                            LightColor = "#206df0",
                            Name = "Antigravity"
                        },
                        new
                        {
                            Id = 14,
                            Category = "database",
                            DarkColor = "#7eb3dd",
                            IconUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg",
                            LightColor = "#336791",
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 15,
                            Category = "devops",
                            DarkColor = "#66afff",
                            IconUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/githubactions/githubactions-original.svg",
                            LightColor = "#2088FF",
                            Name = "GitHub Actions"
                        });
                });

            modelBuilder.Entity("ProfileDataTechData", b =>
                {
                    b.Property<int>("ProfileDataId")
                        .HasColumnType("integer");

                    b.Property<int>("TechnologiesId")
                        .HasColumnType("integer");

                    b.HasKey("ProfileDataId", "TechnologiesId");

                    b.HasIndex("TechnologiesId");

                    b.ToTable("ProfileDataTechData");
                });

            modelBuilder.Entity("ProjectDataTechData", b =>
                {
                    b.Property<int>("ProjectDataId")
                        .HasColumnType("integer");

                    b.Property<int>("TechnologiesId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectDataId", "TechnologiesId");

                    b.HasIndex("TechnologiesId");

                    b.ToTable("ProjectDataTechData");
                });

            modelBuilder.Entity("Portfolio.Server.Models.TechData", b =>
                {
                    b.HasOne("Portfolio.Server.Models.TechCategoryData", null)
                        .WithMany()
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfileDataTechData", b =>
                {
                    b.HasOne("Portfolio.Server.Models.ProfileData", null)
                        .WithMany()
                        .HasForeignKey("ProfileDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Server.Models.TechData", null)
                        .WithMany()
                        .HasForeignKey("TechnologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectDataTechData", b =>
                {
                    b.HasOne("Portfolio.Server.Models.ProjectData", null)
                        .WithMany()
                        .HasForeignKey("ProjectDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Server.Models.TechData", null)
                        .WithMany()
                        .HasForeignKey("TechnologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
