# syntax=docker/dockerfile:1
FROM alpine:3.23

RUN apk add --no-cache aspnetcore9-runtime

RUN adduser -D -u 1000 user
USER user

RUN mkdir -vp "/home/user/app"
WORKDIR /home/user/app
CMD ["/bin/sh", "-c", "/bin/sh"]